[update]
tasks = ["interfaces", "normalize"]

[update.interfaces]
path = "Application/Resources"
defaultToBase = false
ignoreEmptyStrings = false
unstripped = false

[update.normalize]
path = "Application/Resources"
sourceLocale = "en"
harmonizeWithSource = true
sortByKeys = true

[lint]
path = "Application/Resources"
duplicateKeys = true
emptyValues = true
